# student's biography
print("STUDENT'S BIOGRAPHY")
students_list = []
n = int(input("Enter the student list: "))
print("\n")
for i in range(0,n):
     Name = str(input("enter students name:  "))
     students_list.append(Name)
     RegNo = str(input("REGISTRATION NUMBER:  "))
     students_list.append(RegNo)
     Age  = int(input("Age :  "))
     students_list.append(Age)
     Nationality = str(input("enter the student's Nationality:  "))
     students_list.append(Nationality)
     PhoneNo = int(input("Enter the student's phone number:  "))
     students_list.append(PhoneNo)
     BatchYear = int(input("enter student's year of study:  "))
     students_list.append(BatchYear)
     Course =  str(input("Enter student's course of study:  "))
     students_list.append(Course)
     Program = str(input("Enter student's program admitted in:  "))
     students_list.append(Program)
     GraduationYear = int(input("enter the expected year of graduation:  "))
     students_list.append(GraduationYear)
     print("\n")

print(f"Student Name: {Name}")
print(f"Student RegistrationNumber: {RegNo}")
print(f"Student Age: {Age}")
print(f"Student Nationality: {Nationality}")
print(f"Student PhoneNumber: {PhoneNo}")
print(f"Student CurrentyearOfStudy: {BatchYear}")
print(f"Student Course: {Course}")
print(f"Student AdmittedCourse: {Program}")
print(f"Student GraduationYear: {GraduationYear}")
print("WELCOME TO THE CENTER OF SUCCESS THROUGH INNOVATION")